### PR TITLE
-

### PR DESCRIPTION
**Pull request by cuj**
>

### CODE REVIEW

**Comment by codeHusky** [comment]
t

**Comment by 306bobby** [comment]
The project is currently fully broken. I have fixed the setup file but have yet to fix the start file

**Comment by 306bobby** [comment]
> @306bobby Thanks for fixing the project, I have successfully installed android using your fork, but with an issue. touchscreen isn't working, I've installed android before but touch was working. can you please give me any suggestions to fix touch? thanks.

I currently do not have a workaround to fix touch yet, me and a few others are working on it and it hopefully will be fixed soon

**Comment by Joomboosick** [comment]
Hello, my iphone stop on screen with 2 tux
iphone 7 plus 14.7.1 ios

**Comment by pengwius** [comment]
Hi, could you make available latest working version, please?

**Comment by 306bobby** [comment]
> Hi, could you make available latest working version, please?

Yes, it’s on my GitHub. For some reason can’t post the link here

**Comment by pengwius** [comment]
> Yes, it’s on my GitHub. For some reason can’t post the link here

Thanks a lot

**Comment by loyahdev** [comment]
None of the changed scripts have worked I get the same failed to copy scripts error after lots of trouble shooting

**Comment by sweeden-ttu** [comment]
You don't really need that anymore. 

1. Go to asahi Linux web page.  
2. Copy and paste the one line curl script into a terminal
3. Pick the dual boot option.  
4. It will shrink your partition space automatically 
5. Hold down the option key when your Mac boots up you can boot into Linux. 

If you want to use a Linux other than Asahi Linux, have an arm64 USB install disk ready to go.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/corellium/projectsandcastle/pull/42#issuecomment-1114755633

@scott-weeden, this repository contains software that allows iPhones to operate alternative operating-systems, not Macs.

**Review by unforgiven211981 — APPROVED** [review]

**Review by unforgiven211981 — APPROVED** [review]

**Review by RokeJulianLockhart — CHANGES_REQUESTED** [review]
We shouldn't merge this.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/corellium/projectsandcastle/pull/42#event-13345788728

@cuj, thanks. What was the point of this anyway?

**Pull request closed without merging**
